"""Core interfaces and types for the superred framework."""

from superred.core.controller import Controller, ControllerResult, RunResult, TaskResult
from superred.core.interfaces import (
    EventHandler,
    NotApplicable,
    Optimizer,
    SecurityClaim,
    Target,
    Task,
)
from superred.core.types import (
    FEEDBACK,
    MODEL_REQUEST,
    MODEL_RESPONSE,
    ConfigSpec,
    Controllable,
    ControllableInjection,
    ControllablePostCallEvent,
    ControllablePreCallEvent,
    ControllableSpec,
    EvaluationResult,
    Event,
    EventChannel,
    EventEnvelope,
    EventResponse,
    FeedbackResult,
    Goal,
    NoModification,
    Observable,
    ObservableValue,
    QueryParam,
    QuerySpec,
    RequestAnswerPair,
    RunEndEvent,
    RunEndResponse,
    RunStartEvent,
    Score,
    SecurityDomain,
    SecurityDomainTag,
    Trajectory,
    TrajectoryEntry,
    TrajectoryEntryType,
)

__all__ = [
    # Controller
    "Controller",
    "ControllerResult",
    "RunResult",
    "TaskResult",
    # Interfaces
    "EventHandler",
    "NotApplicable",
    "Optimizer",
    "SecurityClaim",
    "Target",
    "Task",
    # Types
    "ConfigSpec",
    "Controllable",
    "ControllableInjection",
    "ControllablePostCallEvent",
    "ControllablePreCallEvent",
    "ControllableSpec",
    "EvaluationResult",
    "Event",
    "EventChannel",
    "EventEnvelope",
    "EventResponse",
    "FEEDBACK",
    "FeedbackResult",
    "Goal",
    "MODEL_REQUEST",
    "MODEL_RESPONSE",
    "NoModification",
    "Observable",
    "ObservableValue",
    "QueryParam",
    "QuerySpec",
    "RequestAnswerPair",
    "RunEndEvent",
    "RunEndResponse",
    "RunStartEvent",
    "Score",
    "SecurityDomain",
    "SecurityDomainTag",
    "Trajectory",
    "TrajectoryEntry",
    "TrajectoryEntryType",
]
