"""Core interfaces and types for the superred framework."""

from superred.core.interfaces import Optimizer
from superred.core.types import (
    FEEDBACK,
    MODEL_REQUEST,
    MODEL_RESPONSE,
    Controllable,
    ControllableInjection,
    ControllablePostCallEvent,
    ControllablePreCallEvent,
    ControllableSpec,
    EvaluationResult,
    Event,
    EventResponse,
    FeedbackResult,
    Goal,
    Observable,
    ObservableValue,
    RequestAnswerPair,
    Score,
    SecurityDomain,
    SecurityDomainTag,
    Trajectory,
    TrajectoryEntry,
    TrajectoryEntryType,
)

__all__ = [
    # Interfaces
    "Optimizer",
    # Types
    "Artifact",
    "Controllable",
    "ControllableInjection",
    "ControllablePostCallEvent",
    "ControllablePreCallEvent",
    "ControllableSpec",
    "EvaluationResult",
    "FEEDBACK",
    "Event",
    "EventResponse",
    "FeedbackResult",
    "Goal",
    "MODEL_REQUEST",
    "MODEL_RESPONSE",
    "Observable",
    "ObservableValue",
    "RequestAnswerPair",
    "Score",
    "SecurityDomain",
    "SecurityDomainTag",
    "Trajectory",
    "TrajectoryEntry",
    "TrajectoryEntryType",
]
